### ISSUE TITLE
新开源MYNLP，能不能抽空帮我一起评测，谢谢

### ISSUE THREAD

**Issue by jimium** [tiandiweizun/chinese-segmentation-evaluation#1]
项目地址[https://github.com/mayabot/mynlp](https://github.com/mayabot/mynlp)

mynlp是一个开源高性能、模块化、可扩展的中文NLP工具包。

设计目标：
- 企业级
- 高性能
- 模块化
- 可扩展
- 多场景
- 柔性API

```
<dependency>
  <groupId>com.mayabot.mynlp</groupId>
  <artifactId>mynlp-segment</artifactId>
  <version>3.0.0</version>
</dependency>
```

只运行基础CORE分词，不开启词性和人名。
```
Lexer lexer = Lexers.builder()
                .basic().core()
                .build();

lexer.scan("今年的2019年9月13日，中秋节快乐")
```

**Comment by tiandiweizun** [comment]
您好，刚看见不好意思，我做了测试，发现有个问题：分词输出结果拼接起来和原有的输入结果不一致，我看了一下，应该是归一化导致的，这会导致评测准确率的时候出现问题。比如：“今年的2019年9月13日，中秋节快乐”中的中文逗号改成了英文逗号，“出现了一大批模糊主题”中的“糊”改成了“煳”，我感觉输出原始结果比较合适，或者如果用户想使用归一化或原始的结果，能否可以通过传入参数进行限定，我在你的git上也开一下issue。

**Comment by tiandiweizun** [comment]
评测结果已经在readme页面上了，速度挺快的
![image](https://user-images.githubusercontent.com/13550295/65213423-b40c3200-dad8-11e9-8045-e6abbbd9881c.png)

**Comment by jimium** [comment]
👍 感谢
